# This file is part of the dune-xt project:
#   https://github.com/dune-community/dune-xt
# The copyright lies with the authors of this file (see below).
# License: BSD 2-Clause License (http://opensource.org/licenses/BSD-2-Clause)
# Authors:
#   Felix Schindler (2016 - 2017)
#
################################
# Dune module information file #
################################

#Name of the module
Module: dune-xt
Version: 18.11-dev
Maintainer: felix.schindler@wwu.de
#depending on
Depends: dune-common (>= 2.6)
